// src/components/About.svelte
<section id="about" class="lg:flex justify-center lg:p-20 text-lg min-h-screen pt-8">

    <div class="lg:w-1/5 pr-5">
        <h1 class="flex lg:justify-end justify-start font-extrabold text-2xl uppercase text-violet-400">
                About
        </h1>
    </div>

    <div class="lg:w-4/5 pl-5">
        <p class="">
            I'm a student at <strong>HKU in Utrecht</strong> where I study <strong>Game Development</strong>


        </p>

        <p>

        </p>
    </div>

</section>

// src/components/About.vue
<template>
    <section id="about" class="section-main">

    <div class="lg:w-1/5 pr-5">
        <h1 class="flex lg:justify-end justify-start font-extrabold text-2xl uppercase text-violet-400">
                About
        </h1>
    </div>

    <div class="lg:w-4/5 pl-5">
        <p class="">
            I'm a student at <strong>HKU in Utrecht</strong> where I study <strong>Game Development</strong>


        </p>

        <p>

        </p>
    </div>

    </section>
</template>
