// src/components/Header.vue
<template>
    <header class="sticky z-[5] top-0 duration-200 px-6 flex items-center justify-between
     border border-solid py-6 bg-slate-900 border-transparent"
     @mouseleave="HideAllMenus()">
        
        <a href="/" class="font-medium">
            <b class="font-bold">Ben</b> Rosenmöller
        </a>

        <HeaderLinksDesktop :tabs="tabs" :tabsWithChildren="tabsWithChildren" />
        <HeaderLinksMobile :tabs="tabs" :tabsWithChildren="tabsWithChildren" />

    </header>
</template>

<script setup>
    import { ref } from 'vue';
    import HeaderLinksDesktop from './HeaderLinksDesktop.vue';
    import HeaderLinksMobile from './HeaderLinksMobile.vue';

    const tabs = ref([
        { 
            name: 'Intro', 
            link: '/#intro' 
        },
        { 
            name: 'About', 
            link: '/#about' 
        },
        { 
            name: 'Timeline', 
            link: '/#timeline' 
        },
        { 
            name: 'Skills', 
            link: '/#skills' 
        },
    ]);

    const tabsWithChildren = ref([
        {
            active: false,
            name: 'Projects', 
            link: '/#projects',
            children: [
                {
                    name: 'Voxel Smith',
                    link: "/voxel-smith"
                },
                {
                    name: 'Enigma Escape',
                    link: "/enigma-escape"
                },
                {
                    name: 'Terrain Generation',
                    link: "/terrain-generation"
                },
                {
                    name: 'Paint Over War',
                    link: "/paint-over-war"
                },
                {
                    name: 'Under Our Wing',
                    link: "/under-our-wing"
                },
            ]
        },
        {
            active: false,
            name: 'Hobbies', 
            link: '/#hobbies',
            children: [
                {
                    name: 'Nevas Buildings',
                    link: "/voxel-smith"
                },
                {
                    name: 'Music',
                    link: "/voxel-smith"
                },
            ]
        },
    ]);
    
    function HideAllMenus(){
        for (let i = 0; i < tabsWithChildren.value.length; i++) {
            const element = tabsWithChildren.value[i];
            element.active = false;
        }
    }
    
</script>

// src/components/Header.svelte
<script>
    export let y;

    let tabs = [
        { name: 'Intro', link: '#intro' },
        { name: 'About', link: '#about' },
        { name: 'Skills', link: '#skills' },
        { name: 'Projects', link: '#projects' },
    ]
</script>

<header class="{'sticky z-[10] top-0 duration-200 px-6 py-2 flex items-center justify-between border border-solid' + 
    (y > 0 ? 'py-4 bg-slate-950 border-violet-950' : 'py-6 bg-transparent border-transparent')}">
    <h1 class="font-medium ">
        <b class="font-bold">Ben</b> Rosenmöller
    </h1>
    <div class="sm:flex items-center gap-4 hidden">
        {#each tabs as tab}
            <a href="{tab.link}" class="duration-200 hover:text-violet-400">
                <p>{tab.name}</p>
            </a>
        {/each}
    </div>
    <!-- <a href="" class="blueShadow relative overflow-hidden px-5 py-2 group rounded-full bg-white text-slate-950">
        <div class="absolute top-0 right-full w-full h-full bg-violet-400 opacity-20 group-hover:translate-x-full z-0 duration-200">

        </div>
        <h4 class="relative z-[9]">
            Get in touch
        </h4>
    </a> -->
</header>
