// src/components/Intro.vue
<template>
    <section id="intro" class="section-main">
        <div class="lg:text-5xl text-2xl">
            <div class="lg:mb-20 mb-10">Hi,</div>
            <div>
                I'm <strong>Ben Rosenmöller</strong>, a passionate Game Developer from The Netherlands, who loves to create, design and learn new things.
            </div>
            <div class="mt-5 lg:text-xl text-lg">
                Contact me at 
                <a href="mailto:rosenmollerben@gmail.com" target="_blank" class="text-violet-400 fancy-link">
                    rosenmollerben@gmail.com
                </a>
            </div>
        </div>

        <div class="lg:ml-10 mb-20 lg:p-0 md:p-20 p-5">
            <img class="h-full object-cover rounded-lg" src="../assets/BenRosenmollerPortrait.jpg" alt="">
        </div>
    </section>
</template>

// src/components/Intro.svelte
<section id="intro" class="lg:flex justify-center lg:p-20 min-h-screen pt-8">
    <div class="lg:text-5xl text-2xl">
        <div class="lg:mb-20 mb-10">Hi,</div>
        <div>
            I'm <strong>Ben Rosenmöller</strong>, a passionate Game Developer from The Netherlands, who loves to create, design and learn new things.
        </div>
        <div class="mt-5 lg:text-xl text-lg">
            Contact me at 
            <a href="mailto:rosenmollerben@gmail.com" target="_blank" class="text-violet-400 fancy-link">
                rosenmollerben@gmail.com
            </a>
        </div>
    </div>

    <div class="lg:ml-10 mb-20 lg:p-0 md:p-20 p-5">
        <img class="h-full object-cover rounded-lg" src="assets/BenRosenmollerPortrait.jpg" alt="">
    </div>
</section>
