// src/components/Projects.svelte
<section id="projects" class="lg:flex justify-center lg:p-20 text-lg min-h-screen pt-8">

    <div class="lg:w-1/5 pr-5">
        <h1 class="flex lg:justify-end justify-start font-extrabold text-2xl uppercase text-violet-400">
                Projects
        </h1>
    </div>

    <div class="lg:w-4/5 pl-5">
        project 1
    </div>
</section>

// src/components/Projects.vue
<template>
    <section id="projects" class="section-main">

        <div class="lg:w-1/5 pr-5">
            <h1 class="flex lg:justify-end justify-start font-extrabold text-2xl uppercase text-violet-400">
                    Projects
            </h1>
        </div>

        <div class="lg:w-4/5 pl-5">
            project 1
        </div>
    </section>
</template>
